### User Register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "firstName" : "abhi",
    "lastName" : "kk",
    "email" : "a@gmail.com",
    "password" : "123",
    "profileImageUrl" : "http://example.com/avatar.png"
}



### login user
POST  http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email" : "a@gmail.com",
    "password" : "123"
}



### read all articles for user
GET http://localhost:4000/user-api/user




### add comments to an article
POST http://localhost:4000/user-api/users-comment
Content-Type: application/json

{
    "uid" : "69aeeaa0a54ded8516c4ea94",
    "articleId" : "69aee3b90251a40e36443ba3",
    "comment" : "Can do better broooo..."
}





### Author Register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
    "firstName" : "lllll",
    "lastName" : "Nark",
    "email" : "hal@gmail.com",
    "password" : "pswd",
    "profileImageUrl" : "http://example.com/avatar.png"
}


### login Author
POST  http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email" : "test2@gmail.com",
    "password" : "123123"
}




###create article
POST http://localhost:4000/author-api/articles
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFlOTIxNDFiOTA1YmYzODIxZjUzZDMiLCJyb2xlIjoiQVVUSE9SIiwiZW1haWwiOiJoYWxAZ21haWwuY29tIiwiaWF0IjoxNzczMDY5MjE2LCJleHAiOjE3NzMwNzI4MTZ9.j50LCwvaHDZKhefYsqUPt1bSFe4z8_37NYgUxY5NShI

{
    "author" : "69afca09faa1f81ee460a067",
    "title": "My New World.",
    "category" : "Life",
    "content" : "example text 2"
}


### read articles from author (protected)
GET http://localhost:4000/author-api/articles/69afca09faa1f81ee460a067


### Update article
PATCH http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author": "69ae92141b905bf3821f53d3",
    "articleId" : "69aee3b90251a40e36443ba3",
    "title": "Bhalu",
    "category" : "comedy",
    "content": "sdjvbskdjv ksjdvbsdjbv "
}


### delete article (soft)
PUT http://localhost:4000/author-api/articles-delete
Content-Type: application/json

{
    "authorId": "69afca09faa1f81ee460a067",
    "articleId" : "69c66a12f0452b0edfb4380a"
}


### restore article
PUT http://localhost:4000/author-api/article-reload
Content-Type: application/json

{
    "authorId": "69afca09faa1f81ee460a067",
    "articleId" : "69c66a12f0452b0edfb4380a"
}


###logout
GET http://localhost:4000/common-api/logout





### change password
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
    "email": "123@gmail.com",
    "currentPassword": "123",
    "newPassword" : "jjk"
}



### Read all articles from admin
GET http://localhost:4000/admin-api/read


### block users
GET http://localhost:4000/admin-api/block/6989a7897ec9f73323d1221a


### unblock user
GET http://localhost:4000/admin-api/un-block/6989a7897ec9f73323d1221a





### checking invalid path route
GET http://localhost:4000/author-api/invalid-path